// High-fidelity Mock Data for CampusPulse
export const initialNotifications = [
    {
        id: '1',
        title: 'Google SDE Intern Drive 2026',
        company: 'Google',
        score: 98,
        type: 'Placement',
        body: 'Google is hiring Software Engineering Interns for Summer 2026. Online Assessment (OA) link is open for eligible candidates. Required CGPA: 8.5+.',
        date: 'Today, 10:30 AM',
        timestamp: '10 mins ago',
        read: false,
        criteria: 'CGPA >= 8.5, CS/IT branch only',
        actionLabel: 'Apply on Portal',
        urgency: 'Critical',
        views: 342
    },
    {
        id: '2',
        title: 'Semester VIII Final Results Published',
        company: 'Academic Cell',
        score: 92,
        type: 'Result',
        body: 'The results for Semester VIII End-Semester examinations have been officially published. Students can view and download their provisional transcript PDF.',
        date: 'Today, 09:15 AM',
        timestamp: '1 hour ago',
        read: false,
        criteria: 'All students',
        actionLabel: 'View Transcript',
        urgency: 'Critical',
        views: 890
    },
    {
        id: '3',
        title: 'Microsoft Codess Hackathon 2026',
        company: 'Microsoft',
        score: 88,
        type: 'Event',
        body: 'Microsoft is hosting its flagship annual mentorship and coding event for female developers. Registrations closing soon. Form link attached.',
        date: 'Yesterday, 04:00 PM',
        timestamp: '18 hours ago',
        read: false,
        criteria: 'Female students, CGPA >= 8.0',
        actionLabel: 'Register Now',
        urgency: 'High',
        views: 512
    },
    {
        id: '4',
        title: 'Uber SDE Placement OA Details',
        company: 'Uber',
        score: 96,
        type: 'Placement',
        body: 'Shortlisted candidates list for the upcoming Uber Coding round. Please confirm your presence by filling out the consent form before 8 PM tonight.',
        date: 'Yesterday, 02:30 PM',
        timestamp: '20 hours ago',
        read: false,
        criteria: 'Shortlisted candidates only',
        actionLabel: 'Confirm Presence',
        urgency: 'Critical',
        views: 284
    },
    {
        id: '5',
        title: 'NVIDIA Hardware Intern Interview Schedule',
        company: 'NVIDIA',
        score: 95,
        type: 'Placement',
        body: 'Technical Interview rounds schedules for hardware interns. Slot selections will lock automatically based on first-come-first-serve.',
        date: 'Yesterday, 11:00 AM',
        timestamp: '23 hours ago',
        read: true,
        criteria: 'Shortlisted hardware candidates',
        actionLabel: 'Book Slot',
        urgency: 'Critical',
        views: 125
    },
    {
        id: '6',
        title: 'CS 304 Database Lab Re-evaluation',
        company: 'Dept of CSE',
        score: 81,
        type: 'Result',
        body: 'Grades for CS304 (DBMS Lab) have been updated following student feedback regarding incorrect marking schemas in mid-semester audits.',
        date: 'June 8, 2026',
        timestamp: '2 days ago',
        read: false,
        criteria: 'CSE Dept - 3rd Year',
        actionLabel: 'Check Grade',
        urgency: 'High',
        views: 198
    },
    {
        id: '7',
        title: 'Annual College Tech Fest "Pulse 2026"',
        company: 'Student Council',
        score: 74,
        type: 'Event',
        body: 'Registration is open for various technical events, coding arenas, robotics challenges, and guest speaker series during Pulse 2026.',
        date: 'June 8, 2026',
        timestamp: '2 days ago',
        read: true,
        criteria: 'Open to all branches',
        actionLabel: 'Explore Fest',
        urgency: 'Medium',
        views: 1120
    },
    {
        id: '8',
        title: 'Adobe Women-in-Technology Scholarship',
        company: 'Adobe',
        score: 87,
        type: 'Placement',
        body: 'Adobe announces WIT Scholarship providing tuition fees and SDE internship opportunities. Final submission deadline extended.',
        date: 'June 7, 2026',
        timestamp: '3 days ago',
        read: false,
        criteria: 'Female candidates, 2nd & 3rd Year',
        actionLabel: 'Submit Application',
        urgency: 'High',
        views: 345
    },
    {
        id: '9',
        title: 'Minor Project Mid-Term Submission',
        company: 'CSE Faculty',
        score: 83,
        type: 'Result',
        body: 'Project reports and Git repository submission link is active. Please upload progress reports signed by respective project guides.',
        date: 'June 7, 2026',
        timestamp: '3 days ago',
        read: true,
        criteria: '4th Year CSE',
        actionLabel: 'Submit Report',
        urgency: 'High',
        views: 172
    },
    {
        id: '10',
        title: 'Amazon Web Services Training & Certifications',
        company: 'AWS Academy',
        score: 79,
        type: 'Event',
        body: 'Free cloud computing certifications vouchers sponsored by university academic credits. Limit: first 200 registered students.',
        date: 'June 6, 2026',
        timestamp: '4 days ago',
        read: true,
        criteria: 'All engineering students',
        actionLabel: 'Claim Voucher',
        urgency: 'Medium',
        views: 654
    },
    {
        id: '11',
        title: 'Placements Guidelines & Resume Freeze',
        company: 'Placement Cell',
        score: 94,
        type: 'Placement',
        body: 'Mandatory verification of resume profiles. Any student with unverified resumes will not be permitted to sit for Google or Uber drives.',
        date: 'June 5, 2026',
        timestamp: '5 days ago',
        read: true,
        criteria: 'Final Year students',
        actionLabel: 'Verify Resume',
        urgency: 'Critical',
        views: 1205
    },
    {
        id: '12',
        title: 'Summer Placement Report 2025-26',
        company: 'Placement Cell',
        score: 72,
        type: 'Result',
        body: 'Official placement statistics, average packages, and top recruiting sectors stats report has been uploaded to the student drive.',
        date: 'June 4, 2026',
        timestamp: '5 days ago',
        read: true,
        criteria: 'All students',
        actionLabel: 'Download Report',
        urgency: 'Medium',
        views: 1450
    },
    {
        id: '13',
        title: 'Intuit SDE Off-Campus Hiring Drive',
        company: 'Intuit',
        score: 85,
        type: 'Placement',
        body: 'Direct referral links provided by alumni pool for Associate Software Engineer role. Please review resume guidelines before applying.',
        date: 'June 4, 2026',
        timestamp: '5 days ago',
        read: false,
        criteria: '2026 Batch Graduates',
        actionLabel: 'Get Referral',
        urgency: 'High',
        views: 402
    },
    {
        id: '14',
        title: 'Robotics Workshop: ROS & Gazebo Sim',
        company: 'Robotics Club',
        score: 64,
        type: 'Event',
        body: 'Hands-on bootcamp on Robot Operating System and simulation stacks. Pre-requisite: basic C++ or Python knowledge.',
        date: 'June 3, 2026',
        timestamp: '6 days ago',
        read: true,
        criteria: 'Open to all',
        actionLabel: 'Register Workshop',
        urgency: 'Low',
        views: 180
    },
    {
        id: '15',
        title: 'TCS Digital Recruitment Results',
        company: 'TCS',
        score: 82,
        type: 'Result',
        body: 'Shortlists for Digital roles package offer. Offer letters will be dispatched via NextPortal profiles over this weekend.',
        date: 'June 2, 2026',
        timestamp: '1 week ago',
        read: true,
        criteria: 'Selected TCS candidates',
        actionLabel: 'View Offer Details',
        urgency: 'High',
        views: 310
    }
];

export const initialProfile = {
    name: 'Alok Kumar',
    email: 'alok.kumar@university.edu',
    cgpa: 8.92,
    branch: 'Computer Science & Engineering',
    semester: 'VIII',
    rollNumber: '2022CSE8092',
    channels: {
        push: true,
        email: true,
        slack: false
    },
    threshold: 70
};
